//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Core/Player/PlayerInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputAction: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputAction"",
    ""maps"": [
        {
            ""name"": ""PlayerActionMaps"",
            ""id"": ""e6ab1c1c-116b-4685-bb2f-14681a3e3fab"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""2f5d643d-4914-45b8-8596-8037105eefb0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""StickDeadzone"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""AimK"",
                    ""type"": ""Value"",
                    ""id"": ""ad9b9a48-8d61-41ce-947d-e2b167f12429"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""AimK1"",
                    ""type"": ""Value"",
                    ""id"": ""6de54ee4-29b4-45c0-a163-5e66275cf8bc"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""AimG"",
                    ""type"": ""Value"",
                    ""id"": ""e548d08d-91da-40a6-8dd7-2030887fc364"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Medkit"",
                    ""type"": ""Button"",
                    ""id"": ""1854978b-72cd-4d51-9ed6-3f7cdd5fa02c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""4ef344b3-cc88-4ee5-9a08-b6a4c938149e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Inventory"",
                    ""type"": ""Button"",
                    ""id"": ""06682d00-4f82-48d5-acbf-c6c1541dff70"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""Button"",
                    ""id"": ""2cd0ff2d-cd9f-45fd-ba6d-162653b359db"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Map"",
                    ""type"": ""Button"",
                    ""id"": ""6ece8c53-cb24-42d6-b533-a074a52347bb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Augment1"",
                    ""type"": ""Button"",
                    ""id"": ""dc2e1319-c66c-4217-b23d-f5abdda0dc40"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Augment2"",
                    ""type"": ""Button"",
                    ""id"": ""91bee19a-b264-4db0-adbb-7725f96cfc65"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Augment3"",
                    ""type"": ""Button"",
                    ""id"": ""f58b5fc0-9c84-4045-8898-589dd3cb732e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Weapon1"",
                    ""type"": ""Button"",
                    ""id"": ""9c188fda-bb8d-4798-96cc-e07b76d24b47"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Weapon2"",
                    ""type"": ""Button"",
                    ""id"": ""e26fe69e-d51d-4ece-bb4a-8716ddf2c008"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7063e833-98ee-4326-a40d-6d289498ad73"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Medkit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4fefe64b-37a2-4391-bb4e-dd0609f8bef8"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Medkit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""451c942f-cf48-4eb5-8fb2-d2b353f809c2"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""98c86c12-fc61-441d-b9f4-3f1116a7f3f1"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d0b0bac-a1e4-43fd-9896-e58e4a70ac9f"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f2a0f4d-101e-4b38-86e1-2d41f6077f60"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""69a35003-8893-4fb8-b401-ed85ae155979"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""336f682d-01ed-42c0-af80-afb34c0fc987"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ec522f66-ac82-4db0-887c-b74d9963e92f"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Map"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f793bcb4-5f51-4d3b-b43a-1b419762f7e1"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Map"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0cf4c3a9-0f2c-42ab-b2b9-b23d6f2f7c0b"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Augment1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87d21d3c-8512-439d-85b2-0b8b88a86450"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Augment1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd6fb3ce-765b-4bf8-9679-6141c5caa60b"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Augment2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""55d8e150-24f4-4cb4-8de3-3a39b9ef0f5f"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Augment2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""529f8409-330b-4cd7-9cea-364b511cd39f"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Augment3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""781d9026-e508-4284-94f5-8624165f9d51"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Augment3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6e007be9-1633-47e4-9ff3-05f26e2dc522"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Weapon1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87598203-1e04-4ee6-bb01-e7e9fdc1f08a"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Weapon1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dc51ff9b-970f-4aae-93a1-949537721da1"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Weapon2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6b0bff3c-0d41-476c-afd5-07b9f1ca0746"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Weapon2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5cd1e57d-5bd4-4f20-b27a-dea084318150"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""AimK"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""6f81e343-0554-45bb-b6c8-e82dffc36562"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""bfd82e38-a91d-4f34-ad4b-69eab9439e49"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""46e09849-a949-49d6-bbcc-e0554a80af50"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""3cf7e18e-5e6b-4853-bcca-c4d908b4ec6b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""5b39098d-b542-4b86-a21b-4da0a6f12889"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""6bc99f5d-1e5c-4236-b319-444ca853d3d8"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""88854856-41dd-41d4-b9b8-3a29def97da7"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""AimG"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1119a424-aae2-404d-8fa4-cf05e52c7475"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""AimG"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de4f0f63-33a2-43cf-85d7-13e6e9629fd4"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""AimK1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // PlayerActionMaps
        m_PlayerActionMaps = asset.FindActionMap("PlayerActionMaps", throwIfNotFound: true);
        m_PlayerActionMaps_Movement = m_PlayerActionMaps.FindAction("Movement", throwIfNotFound: true);
        m_PlayerActionMaps_AimK = m_PlayerActionMaps.FindAction("AimK", throwIfNotFound: true);
        m_PlayerActionMaps_AimK1 = m_PlayerActionMaps.FindAction("AimK1", throwIfNotFound: true);
        m_PlayerActionMaps_AimG = m_PlayerActionMaps.FindAction("AimG", throwIfNotFound: true);
        m_PlayerActionMaps_Medkit = m_PlayerActionMaps.FindAction("Medkit", throwIfNotFound: true);
        m_PlayerActionMaps_Interact = m_PlayerActionMaps.FindAction("Interact", throwIfNotFound: true);
        m_PlayerActionMaps_Inventory = m_PlayerActionMaps.FindAction("Inventory", throwIfNotFound: true);
        m_PlayerActionMaps_Reload = m_PlayerActionMaps.FindAction("Reload", throwIfNotFound: true);
        m_PlayerActionMaps_Map = m_PlayerActionMaps.FindAction("Map", throwIfNotFound: true);
        m_PlayerActionMaps_Augment1 = m_PlayerActionMaps.FindAction("Augment1", throwIfNotFound: true);
        m_PlayerActionMaps_Augment2 = m_PlayerActionMaps.FindAction("Augment2", throwIfNotFound: true);
        m_PlayerActionMaps_Augment3 = m_PlayerActionMaps.FindAction("Augment3", throwIfNotFound: true);
        m_PlayerActionMaps_Weapon1 = m_PlayerActionMaps.FindAction("Weapon1", throwIfNotFound: true);
        m_PlayerActionMaps_Weapon2 = m_PlayerActionMaps.FindAction("Weapon2", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerActionMaps
    private readonly InputActionMap m_PlayerActionMaps;
    private List<IPlayerActionMapsActions> m_PlayerActionMapsActionsCallbackInterfaces = new List<IPlayerActionMapsActions>();
    private readonly InputAction m_PlayerActionMaps_Movement;
    private readonly InputAction m_PlayerActionMaps_AimK;
    private readonly InputAction m_PlayerActionMaps_AimK1;
    private readonly InputAction m_PlayerActionMaps_AimG;
    private readonly InputAction m_PlayerActionMaps_Medkit;
    private readonly InputAction m_PlayerActionMaps_Interact;
    private readonly InputAction m_PlayerActionMaps_Inventory;
    private readonly InputAction m_PlayerActionMaps_Reload;
    private readonly InputAction m_PlayerActionMaps_Map;
    private readonly InputAction m_PlayerActionMaps_Augment1;
    private readonly InputAction m_PlayerActionMaps_Augment2;
    private readonly InputAction m_PlayerActionMaps_Augment3;
    private readonly InputAction m_PlayerActionMaps_Weapon1;
    private readonly InputAction m_PlayerActionMaps_Weapon2;
    public struct PlayerActionMapsActions
    {
        private @PlayerInputAction m_Wrapper;
        public PlayerActionMapsActions(@PlayerInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_PlayerActionMaps_Movement;
        public InputAction @AimK => m_Wrapper.m_PlayerActionMaps_AimK;
        public InputAction @AimK1 => m_Wrapper.m_PlayerActionMaps_AimK1;
        public InputAction @AimG => m_Wrapper.m_PlayerActionMaps_AimG;
        public InputAction @Medkit => m_Wrapper.m_PlayerActionMaps_Medkit;
        public InputAction @Interact => m_Wrapper.m_PlayerActionMaps_Interact;
        public InputAction @Inventory => m_Wrapper.m_PlayerActionMaps_Inventory;
        public InputAction @Reload => m_Wrapper.m_PlayerActionMaps_Reload;
        public InputAction @Map => m_Wrapper.m_PlayerActionMaps_Map;
        public InputAction @Augment1 => m_Wrapper.m_PlayerActionMaps_Augment1;
        public InputAction @Augment2 => m_Wrapper.m_PlayerActionMaps_Augment2;
        public InputAction @Augment3 => m_Wrapper.m_PlayerActionMaps_Augment3;
        public InputAction @Weapon1 => m_Wrapper.m_PlayerActionMaps_Weapon1;
        public InputAction @Weapon2 => m_Wrapper.m_PlayerActionMaps_Weapon2;
        public InputActionMap Get() { return m_Wrapper.m_PlayerActionMaps; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActionMapsActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActionMapsActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionMapsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionMapsActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @AimK.started += instance.OnAimK;
            @AimK.performed += instance.OnAimK;
            @AimK.canceled += instance.OnAimK;
            @AimK1.started += instance.OnAimK1;
            @AimK1.performed += instance.OnAimK1;
            @AimK1.canceled += instance.OnAimK1;
            @AimG.started += instance.OnAimG;
            @AimG.performed += instance.OnAimG;
            @AimG.canceled += instance.OnAimG;
            @Medkit.started += instance.OnMedkit;
            @Medkit.performed += instance.OnMedkit;
            @Medkit.canceled += instance.OnMedkit;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @Inventory.started += instance.OnInventory;
            @Inventory.performed += instance.OnInventory;
            @Inventory.canceled += instance.OnInventory;
            @Reload.started += instance.OnReload;
            @Reload.performed += instance.OnReload;
            @Reload.canceled += instance.OnReload;
            @Map.started += instance.OnMap;
            @Map.performed += instance.OnMap;
            @Map.canceled += instance.OnMap;
            @Augment1.started += instance.OnAugment1;
            @Augment1.performed += instance.OnAugment1;
            @Augment1.canceled += instance.OnAugment1;
            @Augment2.started += instance.OnAugment2;
            @Augment2.performed += instance.OnAugment2;
            @Augment2.canceled += instance.OnAugment2;
            @Augment3.started += instance.OnAugment3;
            @Augment3.performed += instance.OnAugment3;
            @Augment3.canceled += instance.OnAugment3;
            @Weapon1.started += instance.OnWeapon1;
            @Weapon1.performed += instance.OnWeapon1;
            @Weapon1.canceled += instance.OnWeapon1;
            @Weapon2.started += instance.OnWeapon2;
            @Weapon2.performed += instance.OnWeapon2;
            @Weapon2.canceled += instance.OnWeapon2;
        }

        private void UnregisterCallbacks(IPlayerActionMapsActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @AimK.started -= instance.OnAimK;
            @AimK.performed -= instance.OnAimK;
            @AimK.canceled -= instance.OnAimK;
            @AimK1.started -= instance.OnAimK1;
            @AimK1.performed -= instance.OnAimK1;
            @AimK1.canceled -= instance.OnAimK1;
            @AimG.started -= instance.OnAimG;
            @AimG.performed -= instance.OnAimG;
            @AimG.canceled -= instance.OnAimG;
            @Medkit.started -= instance.OnMedkit;
            @Medkit.performed -= instance.OnMedkit;
            @Medkit.canceled -= instance.OnMedkit;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @Inventory.started -= instance.OnInventory;
            @Inventory.performed -= instance.OnInventory;
            @Inventory.canceled -= instance.OnInventory;
            @Reload.started -= instance.OnReload;
            @Reload.performed -= instance.OnReload;
            @Reload.canceled -= instance.OnReload;
            @Map.started -= instance.OnMap;
            @Map.performed -= instance.OnMap;
            @Map.canceled -= instance.OnMap;
            @Augment1.started -= instance.OnAugment1;
            @Augment1.performed -= instance.OnAugment1;
            @Augment1.canceled -= instance.OnAugment1;
            @Augment2.started -= instance.OnAugment2;
            @Augment2.performed -= instance.OnAugment2;
            @Augment2.canceled -= instance.OnAugment2;
            @Augment3.started -= instance.OnAugment3;
            @Augment3.performed -= instance.OnAugment3;
            @Augment3.canceled -= instance.OnAugment3;
            @Weapon1.started -= instance.OnWeapon1;
            @Weapon1.performed -= instance.OnWeapon1;
            @Weapon1.canceled -= instance.OnWeapon1;
            @Weapon2.started -= instance.OnWeapon2;
            @Weapon2.performed -= instance.OnWeapon2;
            @Weapon2.canceled -= instance.OnWeapon2;
        }

        public void RemoveCallbacks(IPlayerActionMapsActions instance)
        {
            if (m_Wrapper.m_PlayerActionMapsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActionMapsActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionMapsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionMapsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActionMapsActions @PlayerActionMaps => new PlayerActionMapsActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IPlayerActionMapsActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnAimK(InputAction.CallbackContext context);
        void OnAimK1(InputAction.CallbackContext context);
        void OnAimG(InputAction.CallbackContext context);
        void OnMedkit(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnInventory(InputAction.CallbackContext context);
        void OnReload(InputAction.CallbackContext context);
        void OnMap(InputAction.CallbackContext context);
        void OnAugment1(InputAction.CallbackContext context);
        void OnAugment2(InputAction.CallbackContext context);
        void OnAugment3(InputAction.CallbackContext context);
        void OnWeapon1(InputAction.CallbackContext context);
        void OnWeapon2(InputAction.CallbackContext context);
    }
}
